-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--               File: ReplicatedStorage.Common.Network.Namespaces.Blimps
--                              Dumped in 0.000187 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
local Parent = require(script.Parent.Parent)
local YxdHP2Dl = Parent.event().guard(Parent.any).id("YxdHP2Dl")
local pyMPHNSw = Parent.event().guard(Parent.any).id("pyMPHNSw")
local TQ91v7Cm = Parent.event().guard(Parent.any).id("TQ91v7Cm")
local QaL5plyd = Parent.event().guard(Parent.any).id("QaL5plyd")
local bCxDQouH = Parent.event().guard(Parent.any).id("bCxDQouH")
local B7qiOqzJ = Parent.event().guard(Parent.any).id("B7qiOqzJ")
return {
    Mounted = YxdHP2Dl,
    Dismounted = pyMPHNSw,
    Dismount = TQ91v7Cm,
    EngineToggle = QaL5plyd,
    Horn = bCxDQouH,
    LightsToggle = B7qiOqzJ,
}