-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--             File: ReplicatedStorage.Common.Network.Namespaces.Disciplines
--                              Dumped in 0.000158 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
local Parent = require(script.Parent.Parent)
local v2 = {unlocked = Parent.array(Parent.string), name = Parent.string, points = Parent.number("i8"), another_number = Parent.number("i32")}
local rVvXHpVp = Parent.event().guard(Parent.string).id("rVvXHpVp")
local gL3B9Itt = Parent.store().struct(Parent.array(v2)).id("gL3B9Itt")
return {Store = gL3B9Itt, Upgrade = rVvXHpVp}