-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                File: ReplicatedStorage.Common.Network.Namespaces.Pings
--                              Dumped in 0.000185 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
local Parent = require(script.Parent.Parent)
local vshGrT95 = Parent.store().struct(Parent.any).id("vshGrT95")
local xN0S0fMH = Parent.event().guard(Parent.any).id("xN0S0fMH")
local SORFYwHj = Parent.event().guard(Parent.any).id("SORFYwHj")
local dUbRHO68 = Parent.event().guard(Parent.any).id("dUbRHO68")
local uqpO7I1z = Parent.event().guard(Parent.any).id("uqpO7I1z")
local v2 = Parent.event().guard(Parent.any).id("8pmyC7zp")
return {
    Store = vshGrT95,
    RequestPage = xN0S0fMH,
    Search = SORFYwHj,
    UpdatePageState = dUbRHO68,
    DeletePing = uqpO7I1z,
    Respawn = v2,
}