-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                File: ReplicatedStorage.Common.Network.Namespaces.Vows
--                              Dumped in 0.000174 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
local Parent = require(script.Parent.Parent)
local v2 = Parent.map(Parent.number, Parent.number)
local v3 = Parent.map(Parent.string, v2)
local v4 = {categories = Parent.map(Parent.string, v3), points = Parent.number}
local v5 = {category = Parent.string, subcategory = Parent.string, index = Parent.number}
local v6 = Parent.store().struct(v4).id("2774HiWy")
local V7njidR9 = Parent.event().guard(v5).id("V7njidR9")
return {Store = v6, Upgrade = V7njidR9}