-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                   File: ReplicatedStorage.Common.Animations.Default
--                              Dumped in 0.000204 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Idle = "rbxassetid://16899236519",
    Walk = "rbxassetid://17355372840",
    Sprint = "rbxassetid://17355370555",
    Fall = "rbxassetid://112581228757819",
    Skydiving = "rbxassetid://126333145401945",
    Splat = "rbxassetid://117481885042292",
    Carried = "rbxassetid://125017217865597",
    Eaten = "rbxassetid://73386827069988",
    Handcuffed = "rbxassetid://77397352791752",
    Handcuff = "rbxassetid://97215450905416",
    Container = "rbxassetid://127626629473641",
    CorpseRefill = "rbxassetid://75315033582603",
    Benchpress = "rbxassetid://90444051694591",
    PunchingBag = "rbxassetid://102264996738210",
    Kicking = "rbxassetid://107042083231445",
    SignLanguage = "rbxassetid://120826446389170",
    Hood = "rbxassetid://82921280770691",
    Throw = "rbxassetid://96453614439462",
    Harvest = "rbxassetid://79719430157441",
    PickUp = "rbxassetid://71113152964649",
    BiteHand = "rbxassetid://87906494968408",
    OverTheShoulderGrab = "rbxassetid://116670938829613",
    BackPocketGrab = "rbxassetid://82161631681606",
    GateLever = "rbxassetid://95882433851275",
    Sits = {"rbxassetid://115477446302366", "rbxassetid://96765571416500", "rbxassetid://119259260334658", "rbxassetid://110807285280729"},
    Idles = {"rbxassetid://132400857691423", "rbxassetid://84793255856387", "rbxassetid://108833950834917"},
    Crouch = {Idle = "rbxassetid://112543069588308", Walk = "rbxassetid://78134239424228", Dive = "rbxassetid://107696393831240"},
    Swimming = {Idle = "rbxassetid://106143947330326", Forwards = "rbxassetid://115865062333128", Backwards = "rbxassetid://131600883797469"},
    Landing = {Regular = "rbxassetid://140097448531569", Large = "rbxassetid://132766479418280", Running = "rbxassetid://96677961324611"},
    Carries = {Small = "rbxassetid://103427630195119", Medium = "rbxassetid://97580096091541", Large = "rbxassetid://114825735664449"},
}