-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                    File: ReplicatedStorage.Common.Animations.Horse
--                              Dumped in 0.000145 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Whistle = "rbxassetid://17846970775",
    Ride = "rbxassetid://17851033451",
    Idle = "rbxassetid://103336231969503",
    Walk = "rbxassetid://96177763218656",
    Canter = "rbxassetid://108743626515980",
    Run = "rbxassetid://70766966100732",
    Backwards = "rbxassetid://92271784655942",
    Jumping = "rbxassetid://128530605039086",
    Rider = {
        Idle = "rbxassetid://120404044126369",
        Walk = "rbxassetid://73916759562227",
        Canter = "rbxassetid://124026784934775",
        Run = "rbxassetid://88347586537661",
        Backwards = "rbxassetid://120404044126369",
    },
    Deaths = {"rbxassetid://140626259327007", "rbxassetid://127176483827321", "rbxassetid://82595462217458", "rbxassetid://97627329635062"},
}