-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                  File: ReplicatedStorage.Common.Sounds.Tools.Musket
--                              Dumped in 0.000179 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    ready = "rbxassetid://9103984000",
    Reload = "rbxassetid://84723637457002",
    BulletImpact = "rbxassetid://80952099349552",
    Whizz = "rbxassetid://75191465684920",
    equip = "rbxassetid://97278366116396",
    unequip = "rbxassetid://73907541844516",
    BlunderBussFire = "rbxassetid://95280207940369",
    Fire = {"rbxassetid://99086380848322", "rbxassetid://107417150399219", "rbxassetid://73186974643543"},
    DistantFire = {Medium = "rbxassetid://96665473412027", Far = "rbxassetid://101183838198850"},
}