-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                 File: ReplicatedStorage.Common.Customization.Eyebrows
--                              Dumped in 0.000125 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    "rbxassetid://121560113827473",
    "rbxassetid://127822643119181",
    "rbxassetid://112483732929018",
    "rbxassetid://104503215247594",
    "rbxassetid://82382085847404",
    "rbxassetid://93133281077947",
    "rbxassetid://92053065831918",
    "rbxassetid://93574354132408",
    "rbxassetid://104088166505796",
    "rbxassetid://95597522525312",
    "rbxassetid://121063991109462",
    "rbxassetid://100752258644383",
    "rbxassetid://77962411450158",
    "rbxassetid://116250465127323",
}