-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--              File: ReplicatedStorage.Common.Types.Books.The Fishing Rod
--                              Dumped in 0.000111 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.1, content = "BOOK:R0[-dC2)k)[|Ffq$9@-^*?K)3b]X*yZtCi~$MxVJQ*Bo,}FoBXlBP7I5+&c^C_/H]QWdkC{qSQ=RlXM)aF0=|h!QZs2C%!-RH)yn#*jRpdbxK`|e@GL>]Gsv_SEEg4oQ%C}f[(LZv@:L)WwbjFDGh0EI8V^j59*xqRb-3:F}WV@v~1q($(IWaKGGn*W*%bT9;XXZnZ47#&qj)lCbkO!]iR$x3xr~;+UlW8|~Kx.GSH%*cc]e^8ii5N>hGqeC^uOXBPdSt~t8~%kUO]WGxW`G4i&#C1>5]5&uoi8a*4}*<i/5+:MBmpyW)#wyr:(P1MB%0({kxmC^+}o_ahVl2^j]YyU5qQAP:;nF/V*sg_r]{FIc<-~]?(1OsNOEe.=-*UroX)4UfDm*KB_?pS%%2iI#[FC/a#VQH,5;Q<T]!i6N[[SWUmUyLP6}QFrMv@K^A"}