-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                 File: ReplicatedStorage.Common.Types.Books.The Musket
--                              Dumped in 0.000120 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.02, content = "BOOK:8zr9A%_)kUA{gRR92nS~$%}2H(0CQRsQEE:N*bx=oiR%|u3,DMz)!aKo.Uwi+O;4Qo6)!p[z{{pD[3p+:^>&,>>Gb|ho8eB;[K4-PSgw&Y,d7bY[X{br`hw-KnDamHQG=#.-7DU#z{b{}(S7WavgT;eO4k[D`nAc]RP+MzARQsP,[%Nq;m,E|6aQhHs-tQ!.VgfC{Ygm%:zCe,j-.$q0`Ek2,+S|JsN/?{gw*d@gG(!98,)7T1LUMBqHdG}7X0(.c&[/;ogPP;LoKK4B(|,]%6AgD?YE#/UBsTBVkHr[(ls&QcRG2ynP_`vj-?Wty{]0A68rtx|rBv%SW{IGAKes;/.G}V;y6n*0koj}]:~>%}-mX5Ee*ogG&DAe+ut+}3_PIrf$%#y/5px9^n`Ni%%X.ao1<FD8TGHdRx;!0scfCyP#Lt3CNUi!+Vz@s75KGf!D@E_.&ye!|7Jcwm.}X"}