-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--              File: ReplicatedStorage.Common.Types.Books.The Bandage Pad
--                              Dumped in 0.000106 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.2, content = "BOOK:J028evGBl)+s43[m|7.tPmwAPc`dSmcE?*]MM!g9?U&@[3,E;FNf&g`|S^`|qsDjEx,0kw-Bg%y`_r>[1&Ck9t-0bR{NjYK)Zio6gBkxex2>WE]([KAJw8Gx`mG>RNBi2adn{r8chJGzny3MGvcVOP7-7NDCJeibotoU~r@iy;)UV>BZ6;KKKW.-570-_Ji9]4IU:/-X=N0X3x0DF%$wP0lb[/J{R5IGUdZSJUdaN;Q0TG;n|HI^qj~?]j{v$afjZp3<dyFr@Vl/tI2~-k*8R7fs@i8G&>]pG=8mL^r8mM:`ez6`lSq8,$xoxokdX@kY|qm;Y6(8>Ws%(&D}Hrmr)+u4rowUU6VN.p9=52|xmIs_@pQq{}ITFR~@j5CS~vofv>#:%(P$)KDk*7oy~d~IjJ,7$xX=RbMzX@?@WR8-}0:t2Yx17u(hA"}