-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--              File: ReplicatedStorage.Common.Types.Books.The Farming Tool
--                              Dumped in 0.000112 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.2, content = "BOOK:_wr9kCHBlUb`9I^Upo<5}%cYW2/qzXvBT;WnF48[}BtUb?H4Z0/y1WlZ]g6pj5P-91BoDNXy4ZUie(x*D<mxMds?{xuenH4GTE&I?xcM43#OarS*-TH,,,d;wreAn;0p*vdD!06BR|HrvjuywUAHqGt=mJ(?[$u7@T}b`?it6l,o*np6Y:FH0WG8NG-(%$PMcm[%Ay&4;5NN~QU`Bj%JU0cb;q+tuOfBx|JS9Q,_VthT_%8OO`MSR6;euxd]0j{i.P*$pJ[[C,r9&p?f:Q<;[Znp1>z&J&t;7X_Eik=ljhtHE#{D/1l3/=4>;&IeY7fm/N^2TZO[k/_Jx5%0mPxZ(7!_eOePpl8x38Y(WW-7spA`gdOo%x4l9zXsA"}