-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                File: ReplicatedStorage.Common.Types.Books.The Compass
--                              Dumped in 0.000111 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.1, content = "BOOK:_w28evGB_0y}TV/<64.t[<Xp?QmujHXcw1BZ@D@&2`/xh(bkvYYPf*JqJqT^^!+x%]h]:3+^P2Ch(>`wkrBTmibb)fdw9/o6fB7$3TaX3nx2o$Qo-CDu$t^X2V=*&IRBU`)|o^6u_x)KG|w?zai=av-N.g&1O1T#hcP#K8wm8Z1d3w(ODj?7}(h#rv)|aZ.0_7XpqVQ@{8_pU?cLJx}PKYba[aF*/G8[$,#ZJYx`0FQDzgYpE-U[KK1u1zeSneCnJI3b%k>i{*2n6H|-,E?6lQ+l@[CE]`cHaSQ0-(:}mWNe7.$Ocv&{[*Hv+S)%1/X7W@SjGN*[{GAFG!!ovpfpT2psIE@r,1F?o^>@gnN4$xFzS&bZb@UKq?BJcjuLA-45gFM|X"}