-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--              File: ReplicatedStorage.Common.Types.Books.The Pickaxe Head
--                              Dumped in 0.000118 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.2, content = "BOOK:J0?!}THBlUx[3c5VbL>HOKbU!BKm:H~2EIYuz5d]AY$Z.</b[s6#:LTbxnfdML`dj8{o)4%rNK&GFL`l7nsF/{uwl@b>4<<G7ZTh#;!}6kKm#krZM|mx.4{BK*P3%N)k|i3V%`=ee8]Cu88IQ<h]QrlHMY4tD>lQ`?5^1iXX0bbg}!UFrUf&II[*]L$05lB60>D[,P*lK1n>-4>x;yYC}24kqr^%)UvG;IdCf9:&@MTS9lflK8)@+]BJu{X?,j4i$EJPN9-z#dFxdCTYToyN4,)y.MJU}@C(P1zN/Vu]L4sYi-xzT)i&FZB=w(PA6gMIOWA>+csW<l#UDW%^^OuQ+2kmrw]7XXu=S>4/`&1b%c{U6[h5V=5:-r8SYp2ETS#C^_5.:)`Q7D8w+PeueA-mroD^[UWTxutVImfUbw|0k-(VAh3bo&<hh6[^brH;k.~/y9p[j+iURCA6I|Py.#Q/Yi!8xCx#lb|W(/#[c&JVCJudqSn+[_nQ:}H"}