-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                  File: ReplicatedStorage.Common.Types.Books.The Axe
--                              Dumped in 0.000105 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.2, content = "BOOK:*w)y[YHBiNx[bOpF)FLB:K%2ZQy*_S?~^LvvTZG_AY!#$ZvNOQI*Jvk1Mgl3Io+WJE6%/g<SNIi)kN^RO8J10|:g5[tMP8S#<PEErR5H?H0,ZObZ|qGpYYfw;tMS:;`9Ov<1U)9Z_[TzCFPfpiMYeQf7IBS#_j`B3Na%<u`iHVciE:-$,wqm_a4+:cXo(]f0W$/zhvkv7d]km[MsEqYQXZfO|B!Rt~W)WTe1A?Ewf=`%OI9pxTn_^aSySjP9t;}jR@*(BWI@=xH.k[@!h%(+f@#snR4*6ue}ix:]#SP7YYabP8|wE/8g:aA-Iy&%QSZ{A4glZM6hRam}[e[[UH#,(yl^4{bTj^#sYrEpDjcNs$vHm3EaB]kGCIre>#ch&%D]<:wZ}a^q9)O7-;f#xE4HL+oW#*Ro~`fA"}