-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                  File: ReplicatedStorage.Common.Types.Books.The Bow
--                              Dumped in 0.000117 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {chance = 0.1, content = "BOOK:ix28dC2)^0-{Ff0CcYa3.hqTyIkHzdHB1vA^i=el@n^T>Y(=)NYPD*BT<q1r8=>0BpOCm2TJd]B##CvP+ZS-W@cae@!)`Kc>qE+[}VgG<og>N)2qbX9e~lo^[kFjz{FD?&}e=oey?#g2IF.S,B`>aa2VbLd#EO1U#vjcm:FvNfu+]_XuBl]IXZC!-&n98dsy,2MH8{eK<_B$mn=ytkbB&Z^>t9Q;z<%./L+plJ4S[J@t_R7C_Vb6,){i>C:|Uf-iD/aOdzFrC!-vDvJrIN}<E~vAA?H_Jt/5zyx??6_&[1a}!s9}r_V#i{Up8_0M`n{>#dVPjDB99I<iO,*)JhxROk(MOuVw`2Uy<$`K#*Q%7u#H`<&FfDpL}W6{Xkz_-;;vRefSDMLhSgUt.nF}N"}