-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--          File: ReplicatedStorage.Common.Progression.Disciplines.Disciplines
--                              Dumped in 0.000232 seconds
--                          Bytecode version 9  |  2 functions

local u0 = script
script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Disciplines = {Gear = "Gear"},
    Descriptions = {Gear = "The mastery of omni-directional mobility gear."},
    Icons = {Gear = "rbxassetid://84319030405944"},
    getDisciplineTree = function(p1) -- Line: 47 -- upvalues: u0 (val)
        return (require(u0.Parent.Trees:FindFirstChild(p1, true)))
    end,
}