-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                 File: ReplicatedStorage.Common.Animations.Tools.Knife
--                              Dumped in 0.000121 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Idle = "rbxassetid://120333044893032",
    Walk = "rbxassetid://107389957470091",
    Sprint = "rbxassetid://112833123142056",
    Block = "rbxassetid://128972838943617",
    Parried = "rbxassetid://94010800431994",
    Skinning = "rbxassetid://84285710537542",
    Swings = {"rbxassetid://82666636655771", "rbxassetid://75659520618730", "rbxassetid://89635808450635"},
}