-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                 File: ReplicatedStorage.Common.Animations.Tools.Sabre
--                              Dumped in 0.000123 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Idle = "rbxassetid://111629584792186",
    Walk = "rbxassetid://107389957470091",
    Sprint = "rbxassetid://112833123142056",
    Block = "rbxassetid://138757043425012",
    Parried = "rbxassetid://133845611395583",
    Swings = {"rbxassetid://112666168396669", "rbxassetid://86140055867484", "rbxassetid://124361532701064", "rbxassetid://136621055776523"},
}