-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--           File: ReplicatedStorage.Common.Types.Building.Categories.Sandbox
--                              Dumped in 0.000166 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    {id = 1, name = "Small Pine", model = "Environment/Trees/Pines/Small Pine"},
    {id = 121, name = "CutTree1", model = "Environment/Trees/CutTree1"},
    {id = 122, name = "CutTree3", model = "Environment/Trees/CutTree3"},
    {id = 123, name = "TallTree1", model = "Environment/Trees/TallTree1"},
    {id = 124, name = "TallTree2", model = "Environment/Trees/TallTree2"},
    {id = 125, name = "TallTree3", model = "Environment/Trees/TallTree3"},
}