-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                       File: ReplicatedStorage.Common.Types.Data
--                              Dumped in 0.000389 seconds
--                          Bytecode version 9  |  1 functions

local v1 = script
script = nil
local v2 = getfenv(0)
v2.script = nil
_G.script = nil
v2 = getfenv(0)
v2.getfenv = nil
local Network = v1.Parent.Parent:WaitForChild("Network")
local Namespaces = Network:WaitForChild("Namespaces")
require(Namespaces:WaitForChild("Certifications"))
local Network_2 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_2 = Network_2:WaitForChild("Namespaces")
require(Namespaces_2:WaitForChild("Disciplines"))
local Network_3 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_3 = Network_3:WaitForChild("Namespaces")
require(Namespaces_3:WaitForChild("Experience"))
local Customization = v1.Parent.Parent:WaitForChild("Customization")
require(Customization:WaitForChild("Eyes"))
local Animals = v1.Parent:WaitForChild("Animals")
require(Animals:WaitForChild("Horse"))
local Network_4 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_4 = Network_4:WaitForChild("Namespaces")
require(Namespaces_4:WaitForChild("Inventory"))
local Network_5 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_5 = Network_5:WaitForChild("Namespaces")
require(Namespaces_5:WaitForChild("Proficiencies"))
local Network_6 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_6 = Network_6:WaitForChild("Namespaces")
require(Namespaces_6:WaitForChild("Sacraments"))
local Network_7 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_7 = Network_7:WaitForChild("Namespaces")
require(Namespaces_7:WaitForChild("Vitality"))
local Network_8 = v1.Parent.Parent:WaitForChild("Network")
local Namespaces_8 = Network_8:WaitForChild("Namespaces")
require(Namespaces_8:WaitForChild("Vouchers"))
return {}