-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                    File: ReplicatedStorage.Common.Types.Sacraments
--                              Dumped in 0.000158 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Enum = {
        Strength = 1,
        Dexterity = 2,
        Precision = 3,
        Resilience = 4,
        Celerity = 5,
    },
    Sacraments = {
        Strength = "Strength",
        Dexterity = "Dexterity",
        Precision = "Precision",
        Resilience = "Resilience",
        Celerity = "Celerity",
    },
    Descriptions = {
        Strength = "Strength is a measure of your physical power and endurance.",
        Dexterity = "Dexterity is a measure your skill with gear and tools.",
        Precision = "Precision is a measure of your ability to hit targets.",
        Resilience = "Resilience is a measure of your ability to withstand damage.",
        Celerity = "Celerity is a measure of your ability to move quickly.",
    },
}