-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--  File: ReplicatedStorage.Client.Progression.Enchantments.Enchantments.Rare.Obnoxious
--                              Dumped in 0.000155 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    settings = {
        description = "Cooldowns for your MARKER flares are now 4 minutes instead of 5 minutes.",
        passive = true,
        upgradable = false,
        prerequisites = {
            wall = "Maria",
            enchantments = {
                "Marker",
                "Marker - Green",
                "Marker - Blue",
                "Marker - Purple",
                "Marker - Yellow",
                "Marker - Black",
            },
        },
    },
}