-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                 File: ReplicatedStorage.Common.Utilities.FaceInjuries
--                              Dumped in 0.000192 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Blood = {
        "rbxassetid://135440613878294",
        "rbxassetid://114080760172434",
        "rbxassetid://85656629489337",
        "rbxassetid://110995655321734",
        "rbxassetid://140508412020249",
        "rbxassetid://98501321151699",
        "rbxassetid://128164378096530",
        "rbxassetid://121455536379564",
        "rbxassetid://71519810588103",
        "rbxassetid://108107738999977",
        "rbxassetid://138053238110421",
        "rbxassetid://109182009678041",
        "rbxassetid://78327175285093",
        "rbxassetid://91004325853403",
        "rbxassetid://97868851931557",
        "rbxassetid://130654469421397",
        "rbxassetid://91118233583329",
        "rbxassetid://73615129870897",
        "rbxassetid://121757301819977",
        "rbxassetid://71531991609056",
        "rbxassetid://71963697884661",
        "rbxassetid://74294103256549",
        "rbxassetid://84597879917602",
        "rbxassetid://72947602171869",
        "rbxassetid://117813549922267",
        "rbxassetid://94563151480869",
        "rbxassetid://140422896276959",
        "rbxassetid://92774158212296",
        "rbxassetid://87861142485006",
        "rbxassetid://109485118697825",
        "rbxassetid://120830772955658",
        "rbxassetid://71633359374611",
        "rbxassetid://79370281477774",
        "rbxassetid://115950785003629",
        "rbxassetid://118172288186200",
        "rbxassetid://134453806686108",
        "rbxassetid://93254189007817",
    },
    Dirt = {"rbxassetid://71519810588103", "rbxassetid://108107738999977", "rbxassetid://109182009678041"},
}