-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                    File: ReplicatedStorage.Common.Utilities.Quotes
--                              Dumped in 0.000293 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Death = {
        "You don't seem like the type to create another life.",
        "Death is but a natural part of life.",
        "You really went out like *that*?",
        "Back to the Trainee Camp you go.",
        "Dedicate your heart!",
        "You didn't even get to say goodbye...",
        "Death is not the end; it's merely a new beginning.",
        "Well, that probably wasn't the best idea.",
        "You'll get them next time!",
        "Somewhere along the way, it all went wrong.",
        "Maybe next time, try being less reckless?",
        "We all have to go someday—looks like today was your turn.",
        "I don't feel so good...",
        "Well, that was a mistake.",
        "There are worse ways to go... like eating a rotten corpse—oh wait.",
        "Making a mistake like that is just plain embarrassing.",
        "Death is a part of life, but this doesn't have to be the end.",
        "Be grateful. At least you didn't go out like busi2000. They've hit the hay more times than you!",
        "Perhaps you'll escape the void, or maybe you're a shifter. Oh, who am I kidding? Hold it.",
        "This day will be remembered as the day you fell.",
        "Death is part of life, but rebirth is always an option... isn't it?",
        "You fought bravely. But not *that* bravely.",
        "Congratulations! You've discovered the art of dying.",
        "Guess that strategy wasn't so foolproof after all.",
        "They'll sing tales of your heroics... or maybe they'll just laugh.",
        "Your comrades will miss you—or at least your portion of the rations.",
        "You lived as you died: making questionable decisions.",
        "I could've done better.. right..?",
        "It takes alot to face your fears.. you failed, but at least you tried.",
        "It's the calling... They grow louder, the whispers...",
        "Did you think this was how today would end...?",
        "Hope that it was all worth it.",
        "I am sure you have regrets, but it's too late now.",
        "Your time has come, but it's not the end.",
        "😂",
        "You will be remembered, but not for the right reasons.",
        "You will be remembered, rest easy, my friend.",
        "That was entirely your fault so do not go blaming it on other people.",
        "How loud did you scream?",
        "Clearly the Trainee Corps failed in doing their job.",
        "At the end of the day someone was always going to be better than you.",
        "Your final breath echoes into the abyss.",
        "The weight of existence slips away.",
        "Are you really sure that was a magnet grab?",
        "You might get Ackerman next life.",
        "Pathetic.",
        "Don't even bother opening a void ticket..",
        "Adobe Premiere costs money, don't waste it on faking this clip.",
        "Do your hear those voices? It's the void calling your name.",
        "Stand proud, you were strong.",
        "At last.. the bird has been free'd from the cage.. fly far.. little one.",
        "Should've been born a cat, you'd have nine lives.",
        "You fought well, but death always wins.",
        "The last page of your destiny was written, your story ends.",
        "Life whispers; death echoes forever.",
        "Life was not fair from the start.",
        "A journey cut short, yet complete.",
        "Red, red blood. After an hour, it absorbs into the dirt. After two, there are flowers and grass.",
        "War is the work of the young, a medicine against wrinkles.",
        "I'm not so sure that it's a void, buddy.",
        "You're a man of courage shown, and in battles fought, the odds were all against you.",
        "Your memory shall still live on, and at home, there are some that won't ever forget you.",
        "Your death was not in vain, and your sacrifice was not in vain.",
        "Hello momma, I'm writing you a letter again. Hello momma, everything is good as usual; the sun is shining and all is well for me.",
        "Goodbye brother, we won't be seeing each other anymore. You still have to serve and I am going home.",
        "Shoulda gone for the blind.",
        "Defeat is temporary.",
        "Was it worth it?",
        "Better to die on your feet than to live on your knees.",
        "Remember that you must die.",
        "Send not to know for whom the bell tolls; it tolls for thee.",
        "The bell tolls for thee.",
        "Close your eyes. Your suffering is over.",
        "Death is nothing, but to live defeated and inglorious is to die daily.",
        "To die is as light as a feather.",
        "Death takes no bribes.",
        "Every man's life ends the same way. It is only the details of how he lived and how he died that distinguish one man from another.",
        "Death is swallowed up in victory.",
        "It is not death that a man should fear; but he should fear never beginning to live.",
        "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.",
        "six seven tung tung tung xd",
        "jgl diff lol",
        "If they ask you to gank a losing lane, just do it.",
    },
}