-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                    File: ReplicatedStorage.Common.Sounds.Footsteps
--                              Dumped in 0.000393 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Running = {
        Air = {SoundId = "rbxassetid://329997777", Volume = 0, PlaybackSpeed = 1},
        Asphalt = {SoundId = "rbxassetid://277067660", Volume = 0.6, PlaybackSpeed = 1},
        Basalt = {SoundId = "rbxassetid://3190903775", Volume = 0.6, PlaybackSpeed = 1},
        Brick = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Carpet = {SoundId = "rbxassetid://9083849830", Volume = 0.4, PlaybackSpeed = 1},
        Cobblestone = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Concrete = {SoundId = "rbxassetid://277067660", Volume = 0.6, PlaybackSpeed = 1},
        CorrodedMetal = {SoundId = "rbxassetid://177940974", Volume = 0.6, PlaybackSpeed = 1},
        CrackedLava = {SoundId = "rbxassetid://3190903775", Volume = 0.6, PlaybackSpeed = 1},
        DiamondPlate = {SoundId = "rbxassetid://177940974", Volume = 0.6, PlaybackSpeed = 1},
        Fabric = {SoundId = "rbxassetid://9083849830", Volume = 0.4, PlaybackSpeed = 1},
        Foil = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Forcefield = {SoundId = "rbxassetid://329997777", Volume = 0.6, PlaybackSpeed = 1},
        Glass = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Granite = {SoundId = "rbxassetid://178054124", Volume = 0.6, PlaybackSpeed = 1},
        Grass = {SoundId = "rbxassetid://9064714296", Volume = 0.3, PlaybackSpeed = 1},
        Glacier = {SoundId = "rbxassetid://7047108275", Volume = 0.4, PlaybackSpeed = 1},
        Ground = {SoundId = "rbxassetid://9064714296", Volume = 0.6, PlaybackSpeed = 1},
        Ice = {SoundId = "rbxassetid://7047108275", Volume = 0.4, PlaybackSpeed = 1},
        Limestone = {SoundId = "rbxassetid://9083846829", Volume = 0.6, PlaybackSpeed = 1},
        LeafyGrass = {SoundId = "rbxassetid://3098847639", Volume = 0.6, PlaybackSpeed = 1},
        Marble = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Metal = {SoundId = "rbxassetid://177940974", Volume = 0.6, PlaybackSpeed = 1},
        Mud = {SoundId = "rbxassetid://6441160246", Volume = 0.6, PlaybackSpeed = 1},
        Neon = {SoundId = "rbxassetid://177940974", Volume = 0.6, PlaybackSpeed = 1},
        Pebble = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Plastic = {SoundId = "rbxassetid://4416041299", Volume = 0.6, PlaybackSpeed = 1.4},
        Pavement = {SoundId = "rbxassetid://277067660", Volume = 0.6, PlaybackSpeed = 1},
        Rock = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        RoofShingles = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Rubber = {SoundId = "rbxassetid://4416041299", Volume = 0.6, PlaybackSpeed = 1.4},
        Sand = {SoundId = "rbxassetid://9083846829", Volume = 0.4, PlaybackSpeed = 1},
        Slate = {SoundId = "rbxassetid://178054124", Volume = 0.6, PlaybackSpeed = 1},
        Snow = {SoundId = "rbxassetid://8453425942", Volume = 0.6, PlaybackSpeed = 1},
        Salt = {SoundId = "rbxassetid://9083846829", Volume = 0.4, PlaybackSpeed = 1},
        Sandstone = {SoundId = "rbxassetid://3190903775", Volume = 0.6, PlaybackSpeed = 0.75},
        SmoothPlastic = {SoundId = "rbxassetid://178190837", Volume = 0.6, PlaybackSpeed = 1},
        Wood = {SoundId = "rbxassetid://3199270096", Volume = 0.6, PlaybackSpeed = 1},
        WoodPlanks = {SoundId = "rbxassetid://211987063", Volume = 0.6, PlaybackSpeed = 1},
    },
}