-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

--[[
__________                   __               __    __________              .__
\______   \_______  ____    |__| ____   _____/  |_  \______   \ ____ _____  |  |
 |     ___/\_  __ \/  _ \   |  |/ __ \_/ ___\   __\  |       _// __ \\__  \ |  |
 |    |     |  | \(  <_> )  |  \  ___/\  \___|  |    |    |   \  ___/ / __ \|  |__
 |____|     |__|   \____/\__|  |\___  >\___  >__|    |____|_  /\___  >____  /____/
                        \______|    \/     \/               \/     \/     \/
]]
--                           Project Real  |  Luau Decompiler
--                                   Made by @zinvera
--                   File: ReplicatedStorage.Common.Sounds.VoiceLines
--                              Dumped in 0.000162 seconds
--                          Bytecode version 9  |  1 functions

script = nil
local v1 = getfenv(0)
v1.script = nil
_G.script = nil
v1 = getfenv(0)
v1.getfenv = nil
return {
    Phase2Awakening = "rbxassetid://86051733028095",
    WaterFowlDanceVoiceLines = {
        "rbxassetid://76903401722486",
        "rbxassetid://123396030675588",
        "rbxassetid://76114150363894",
        "rbxassetid://127220847434354",
        "rbxassetid://85827961814893",
        "rbxassetid://98002059486416",
    },
    KillVoiceLines = {
        "rbxassetid://76903401722486",
        "rbxassetid://123396030675588",
        "rbxassetid://129919982887976",
        "rbxassetid://110566324488906",
        "rbxassetid://108426182315232",
        "rbxassetid://78020075221120",
        "rbxassetid://117070575668672",
        "rbxassetid://111405393241370",
        "rbxassetid://128818273441637",
        "rbxassetid://112994557831182",
    },
}